version: "3.3"

services:
  bedrock:
    # Minecraft Bedrock server.
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      SERVER_NAME: Oberrieden
      LEVEL_NAME: mesa_2021
      LEVEL_SEED: 128388
      DEFAULT_PLAYER_PERMISSION_LEVEL: visitor
      DIFFICULTY: hard
      # Ops:
      # - Wintermuth (2533274964742991)
      OPS: 2533274964742991
      # Members:
      # - Elzza8077 (2535426640522603)
      # - UrsliBurgonya (2535412700806819)
      MEMBERS: 2535426640522603,2535412700806819
    ports:
      - 19132:19132/udp
    volumes:
      - ./bedrock:/data
    restart: always
    stdin_open: true
    tty: true
  bind:
    # BIND9 DNS server.
    # Used for DNS interception on the Nintendo Switch.
    image: bind
    build: bind/.
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 127.0.0.1:953:953/tcp
    restart: always
