version: "3.9"

services:
  bedrock:
    # Minecraft Bedrock server.
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      SERVER_NAME: Oberrieden
      LEVEL_NAME: mesa_2021
      LEVEL_SEED: 128388
      DEFAULT_PLAYER_PERMISSION_LEVEL: visitor
      DIFFICULTY: hard
    ports:
      - 19132:19132/udp
    volumes:
      - ./bedrock:/data
    stdin_open: true
    tty: true
  bind:
    # BIND9 DNS server.
    # Used for DNS interception on the Nintendo Switch.
    image: bind
    build: bind/.
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 127.0.0.1:953:953/tcp
